name: "Semantic Check"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  contents: read
  pull-requests: read
jobs:
  main:
    name: Semantic Commit Message Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        name: Check PR for Semantic Commit Message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          validateSingleCommit: true
          ignoreLabels: release merge
